In [98]:
import numpy as np

x = np.array([1,2,3])
print(x)
print(x.sum())
print(x.prod())
print(x.mean())
print(x.max())
print(x.min())
print(x.std())
print(x.var())
print(x.size)

print(x.shape)
print(x.ndim)

y = np.array([4,9,16])
print(np.sqrt(y))
print(np.sin(y))
print(np.cos(y))





[1 2 3]
6
6
2.0
3
1
0.816496580927726
0.6666666666666666
3
(3,)
1
[2. 3. 4.]
[-0.7568025   0.41211849 -0.28790332]
[-0.65364362 -0.91113026 -0.95765948]
