In [ ]:
import numpy as np



y = np.array([[1,2,3],[4,5,6]])
print(y)
print(y.shape)
print(y.ndim)
print(y.prod())

z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)


a = np.array([1,2,3])
b = np.array([2,2,2])
print(a + b)
print(a + 5)
print(a - 1)
print(a * 2)





[1 2 3]
6
6
2.0
3
1
0.816496580927726
0.6666666666666666
3
(3,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2
720
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64
9
[3 4 5]
[6 7 8]
[0 1 2]
[2 4 6]
