In [ ]:
import numpy as np

print(np.linspace(0, 1, 5))
print(np.linspace(0, 1, 5, endpoint=False))
print(np.linspace(0, 1, 5, retstep=True))
print(np.random.rand(5))
print(np.random.randn(5))
print(np.random.randint(0, 10, 5))
print(np.random.choice([1, 2, 3, 4, 5], size=3))
print(np.random.choice([1, 2, 3, 4, 5], size=3, replace=False))
print(np.random.choice([1, 2, 3, 4, 5], p=[0.1, 0.2, 0.3, 0.2, 0.2], size=3))
print(np.random.permutation([1, 2, 3, 4, 5]))
print(np.random.shuffle([1, 2, 3, 4, 5]))


[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)
[0.39990521 0.97672524 0.82317402 0.52248104 0.12322265]
[ 0.08685916  0.32931579  0.39482574 -0.58123517 -0.8955094 ]
[0 9 9 7 3]
[4 4 1]
[3 2 1]
[2 1 4]
[3 4 1 2 5]
None
